<a href="https://colab.research.google.com/github/Brenhv/Actividad3_Valores_At-picos_por_Dataframe/blob/main/Actividad_3_(Valores_At%C3%ADpicos_por_Dataframe).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/Gastos y costos 20-23.xlsx')
df

,CALOR Y CONTROL S.A DE C.V,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,GASTO,10418041.6,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,DEDUCCIONES 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IVA,1597941.439,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RET IVA,198890.4,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RET ISR,66039.89,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3342,2020-12-01 00:00:00,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1,129.79,20.21,0,0,150,150,I,Vigente,NaN,0
3343,2020-12-01 00:00:00,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1,2284.8,365.57,0,0,2650.37,2650.37,I,Vigente,NaN,0
3344,2020-12-01 00:00:00,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1,163.79,26.21,0,0,190,190,I,Vigente,NaN,0
3345,2020-12-01 00:00:00,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1,0,0,0,0,0,0,I,Vigente,NaN,0
3346,2020-12-01 00:00:00,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1,14889.29,0,0,0,14889.29,14889.29,I,Vigente,NaN,0

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3347 entries, 0 to 3346
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CALOR Y CONTROL S.A DE C.V  3344 non-null   object
 1   Unnamed: 1                  3154 non-null   object
 2   Unnamed: 2                  3343 non-null   object
 3   Unnamed: 3                  3343 non-null   object
 4   Unnamed: 4                  3343 non-null   object
 5   Unnamed: 5                  3343 non-null   object
 6   Unnamed: 6                  841 non-null    object
 7   Unnamed: 7                  3343 non-null   object
 8   Unnamed: 8                  2952 non-null   object
 9   Unnamed: 9                  3309 non-null   object
 10  Unnamed: 10                 3075 non-null   object
 11  Unnamed: 11                 3343 non-null   object
 12  Unnamed: 12                 3343 non-null   object
 13  GASTO                       3346 non-null   object
 14  10418041.6                  3346 non-null   object
 15  Unnamed: 15                 3342 non-null   object
 16  Unnamed: 16                 3343 non-null   object
 17  Unnamed: 17                 22 non-null     object
 18  Unnamed: 18                 3343 non-null   object
dtypes: object(19)
memory usage: 496.9+ KB

In [69]:
val_nul = df.isnull().sum()
val_nul

CALOR Y CONTROL S.A DE C.V       3
Unnamed: 1                     193
Unnamed: 2                       4
Unnamed: 3                       4
Unnamed: 4                       4
Unnamed: 5                       4
Unnamed: 6                    2506
Unnamed: 7                       4
Unnamed: 8                     395
Unnamed: 9                      38
Unnamed: 10                    272
Unnamed: 11                      4
Unnamed: 12                      4
GASTO                            1
10418041.6                       1
Unnamed: 15                      5
Unnamed: 16                      4
Unnamed: 17                   3325
Unnamed: 18                      4
dtype: int64

In [70]:
df = df.drop(range(0,4))
df.columns = df.iloc[0]
df = df[1:]
df

4,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
5,2020-01-01 00:00:00,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1,0,2248.28,0,0,2248.28,16300,I,Vigente,NaN,14051.72
6,2020-01-01 00:00:00,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1,490,78.4,0,0,568.4,568.4,I,Vigente,NaN,0
7,2020-01-01 00:00:00,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1,195,31.2,0,0,226.2,226.2,I,Vigente,NaN,0
8,2020-01-01 00:00:00,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1,10694.25,1711.08,0,0,12405.33,12405.33,I,Vigente,NaN,0
9,2020-01-01 00:00:00,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1,0,NaN,0,0,0,0,P,Vigente,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3342,2020-12-01 00:00:00,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1,129.79,20.21,0,0,150,150,I,Vigente,NaN,0
3343,2020-12-01 00:00:00,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1,2284.8,365.57,0,0,2650.37,2650.37,I,Vigente,NaN,0
3344,2020-12-01 00:00:00,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1,163.79,26.21,0,0,190,190,I,Vigente,NaN,0
3345,2020-12-01 00:00:00,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1,0,0,0,0,0,0,I,Vigente,NaN,0
3346,2020-12-01 00:00:00,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1,14889.29,0,0,0,14889.29,14889.29,I,Vigente,NaN,0

In [71]:
df['GASTO'].mode()

0    COMPRA
Name: GASTO, dtype: object

In [72]:
df['GASTO'] = df['GASTO'].fillna('COMPRA')

In [73]:
df['TC'] = df['TC'].fillna(1)

In [74]:
df['IMPORTE'].median()

490.0

In [75]:
df['IMPORTE'] = df['IMPORTE'].fillna(490)

In [76]:
df['IVA'] = df['IVA'].fillna(df['IVA'].mean())

In [77]:
df['TIPO'] = df['TIPO'].fillna('I')

In [78]:
df['POLIZA'] = df['POLIZA'].replace('NO LOS METI', 'PE07-ENE20')
df['POLIZA'] = df['POLIZA'].fillna('PE07-ENE20')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3342 entries, 5 to 3346
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3342 non-null   object
 1   FOLIO        3153 non-null   object
 2   UUID         3342 non-null   object
 3   RFC          3342 non-null   object
 4   PROVEEDOR    3342 non-null   object
 5   TIPO GASTO   3342 non-null   object
 6   GASTO        3342 non-null   object
 7   DESCRIPCION  3342 non-null   object
 8   TC           3342 non-null   float64
 9   IMPORTE      3342 non-null   float64
 10  IVA          3342 non-null   float64
 11  RET ISR      3342 non-null   object
 12  RET IVA      3342 non-null   object
 13  TOTAL MX     3342 non-null   object
 14  TOTAL SAT    3342 non-null   object
 15  TIPO         3342 non-null   object
 16  STATUS       3342 non-null   object
 17  POLIZA       3342 non-null   object
 18  Columna1     3342 non-null   object
dtypes: float64(3), object(16)
memory usage: 496.2+ KB

In [80]:
df.isnull().sum()

4
FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC               0
IMPORTE          0
IVA              0
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             0
STATUS           0
POLIZA           0
Columna1         0
dtype: int64

In [81]:
df['POLIZA'].value_counts()

PE07-ENE20    3325
PE03-ENE20       1
PE51-ENE20       1
PE54-ENE20       1
PE53-ENE20       1
PE50-ENE20       1
PE48-ENE20       1
PE46-ENE20       1
PE39-ENE20       1
PE36-ENE20       1
PE4ENE20         1
PE31-ENE20       1
PE09-ENE20       1
PE02-ENE20       1
PE06-ENE20       1
PE05-ENE20       1
PE04-ENE20       1
PE49-ENE20       1
Name: POLIZA, dtype: int64

In [82]:
df['FOLIO'].value_counts()

8811090280022099          16
0001010100750847116902    13
0001010100752163714102    10
22                         4
19                         4
                          ..
1194                       1
964                        1
6191                       1
1958                       1
1044477                    1
Name: FOLIO, Length: 2975, dtype: int64

In [83]:
df = df.drop('FOLIO', axis=1)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3342 entries, 5 to 3346
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA        3342 non-null   object
 1   UUID         3342 non-null   object
 2   RFC          3342 non-null   object
 3   PROVEEDOR    3342 non-null   object
 4   TIPO GASTO   3342 non-null   object
 5   GASTO        3342 non-null   object
 6   DESCRIPCION  3342 non-null   object
 7   TC           3342 non-null   float64
 8   IMPORTE      3342 non-null   float64
 9   IVA          3342 non-null   float64
 10  RET ISR      3342 non-null   object
 11  RET IVA      3342 non-null   object
 12  TOTAL MX     3342 non-null   object
 13  TOTAL SAT    3342 non-null   object
 14  TIPO         3342 non-null   object
 15  STATUS       3342 non-null   object
 16  POLIZA       3342 non-null   object
 17  Columna1     3342 non-null   object
dtypes: float64(3), object(15)
memory usage: 470.1+ KB

In [85]:
df['RET ISR'] = df['RET ISR'].astype('float')
df['RET IVA'] = df['RET IVA'].astype('float')
df['TOTAL MX'] = df['TOTAL MX'].astype('float')
df['TOTAL SAT'] = df['TOTAL SAT'].astype('float')

In [86]:
df2 = df[['TC', 'IMPORTE', 'IVA', 'RET ISR', 'RET IVA', 'TOTAL MX', 'TOTAL SAT']]
df2

4      TC   IMPORTE          IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT
5     1.0      0.00  2248.280000      0.0      0.0   2248.28   16300.00
6     1.0    490.00    78.400000      0.0      0.0    568.40     568.40
7     1.0    195.00    31.200000      0.0      0.0    226.20     226.20
8     1.0  10694.25  1711.080000      0.0      0.0  12405.33   12405.33
9     1.0      0.00   519.824801      0.0      0.0      0.00       0.00
...   ...       ...          ...      ...      ...       ...        ...
3342  1.0    129.79    20.210000      0.0      0.0    150.00     150.00
3343  1.0   2284.80   365.570000      0.0      0.0   2650.37    2650.37
3344  1.0    163.79    26.210000      0.0      0.0    190.00     190.00
3345  1.0      0.00     0.000000      0.0      0.0      0.00       0.00
3346  1.0  14889.29     0.000000      0.0      0.0  14889.29   14889.29

[3342 rows x 7 columns]

In [87]:
y=df
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

Limite superior permitido 4
TC               4.239688
IMPORTE      25155.492600
IVA           4563.167626
RET ISR        667.271992
RET IVA        958.239955
TOTAL MX     28488.002843
TOTAL SAT    33250.398514
Columna1     14626.999268
dtype: float64
Limite inferior permitido 4
TC              -2.129870
IMPORTE     -18910.907561
IVA          -3523.518023
RET ISR       -627.750813
RET IVA       -839.215179
TOTAL MX    -21455.655297
TOTAL SAT   -25762.462834
Columna1    -14171.411134
dtype: float64

<ipython-input-87-a4ee4ef6f795>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-87-a4ee4ef6f795>:2: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-87-a4ee4ef6f795>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()
<ipython-input-87-a4ee4ef6f795>:3: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()

In [88]:
df3= df2[(y<=Limite_Superior)&(y>=Limite_Inferior)]
df3

<ipython-input-88-e341c3d5ee16>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df3= df2[(y<=Limite_Superior)&(y>=Limite_Inferior)]

4      TC   IMPORTE          IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT
5     1.0      0.00  2248.280000      0.0      0.0   2248.28   16300.00
6     1.0    490.00    78.400000      0.0      0.0    568.40     568.40
7     1.0    195.00    31.200000      0.0      0.0    226.20     226.20
8     1.0  10694.25  1711.080000      0.0      0.0  12405.33   12405.33
9     1.0      0.00   519.824801      0.0      0.0      0.00       0.00
...   ...       ...          ...      ...      ...       ...        ...
3342  1.0    129.79    20.210000      0.0      0.0    150.00     150.00
3343  1.0   2284.80   365.570000      0.0      0.0   2650.37    2650.37
3344  1.0    163.79    26.210000      0.0      0.0    190.00     190.00
3345  1.0      0.00     0.000000      0.0      0.0      0.00       0.00
3346  1.0  14889.29     0.000000      0.0      0.0  14889.29   14889.29

[3342 rows x 7 columns]

In [89]:
valores_nulos=df3.isnull().sum()
valores_nulos

4
TC            9
IMPORTE      67
IVA          58
RET ISR      21
RET IVA      74
TOTAL MX     65
TOTAL SAT    45
dtype: int64

In [90]:
df_clean=df3.copy()
df_clean=df_clean.fillna(round(df3.mean(),1))
df_clean

4      TC   IMPORTE          IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT
5     1.0      0.00  2248.280000      0.0      0.0   2248.28   16300.00
6     1.0    490.00    78.400000      0.0      0.0    568.40     568.40
7     1.0    195.00    31.200000      0.0      0.0    226.20     226.20
8     1.0  10694.25  1711.080000      0.0      0.0  12405.33   12405.33
9     1.0      0.00   519.824801      0.0      0.0      0.00       0.00
...   ...       ...          ...      ...      ...       ...        ...
3342  1.0    129.79    20.210000      0.0      0.0    150.00     150.00
3343  1.0   2284.80   365.570000      0.0      0.0   2650.37    2650.37
3344  1.0    163.79    26.210000      0.0      0.0    190.00     190.00
3345  1.0      0.00     0.000000      0.0      0.0      0.00       0.00
3346  1.0  14889.29     0.000000      0.0      0.0  14889.29   14889.29

[3342 rows x 7 columns]

In [91]:
valores_nulos=df_clean.isnull().sum()
valores_nulos

4
TC           0
IMPORTE      0
IVA          0
RET ISR      0
RET IVA      0
TOTAL MX     0
TOTAL SAT    0
dtype: int64

PROCEDIMIENTO "CUANTILES" PARA SUSTITUIR OUTLIERS EN DATAFRAME

In [92]:
y=df2

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido 4
TC              1.000000
IMPORTE      6929.045000
IVA          1280.695753
RET ISR         0.000000
RET IVA         0.000000
TOTAL MX     7983.177500
TOTAL SAT    8269.283750
dtype: float64
Limite inferior permitido 4
TC              1.000000
IMPORTE     -4127.075000
IVA          -748.293452
RET ISR         0.000000
RET IVA         0.000000
TOTAL MX    -4783.142500
TOTAL SAT   -4832.966250
dtype: float64

In [93]:
df3_iqr= df2[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
df3_iqr

4      TC  IMPORTE         IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT
5     1.0     0.00         NaN      0.0      0.0   2248.28        NaN
6     1.0   490.00   78.400000      0.0      0.0    568.40     568.40
7     1.0   195.00   31.200000      0.0      0.0    226.20     226.20
8     1.0      NaN         NaN      0.0      0.0       NaN        NaN
9     1.0     0.00  519.824801      0.0      0.0      0.00       0.00
...   ...      ...         ...      ...      ...       ...        ...
3342  1.0   129.79   20.210000      0.0      0.0    150.00     150.00
3343  1.0  2284.80  365.570000      0.0      0.0   2650.37    2650.37
3344  1.0   163.79   26.210000      0.0      0.0    190.00     190.00
3345  1.0     0.00    0.000000      0.0      0.0      0.00       0.00
3346  1.0      NaN    0.000000      0.0      0.0       NaN        NaN

[3342 rows x 7 columns]

In [94]:
valores_nulos=df3_iqr.isnull().sum()
valores_nulos

4
TC             9
IMPORTE      424
IVA          347
RET ISR       45
RET IVA      253
TOTAL MX     420
TOTAL SAT    426
dtype: int64

In [95]:
df5_iqr=df3_iqr.copy()
df5_iqr=df5_iqr.fillna(round(df3_iqr.mean(),1))
df5_iqr

4      TC  IMPORTE         IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT
5     1.0     0.00  222.200000      0.0      0.0   2248.28    1333.00
6     1.0   490.00   78.400000      0.0      0.0    568.40     568.40
7     1.0   195.00   31.200000      0.0      0.0    226.20     226.20
8     1.0  1082.00  222.200000      0.0      0.0   1239.10    1333.00
9     1.0     0.00  519.824801      0.0      0.0      0.00       0.00
...   ...      ...         ...      ...      ...       ...        ...
3342  1.0   129.79   20.210000      0.0      0.0    150.00     150.00
3343  1.0  2284.80  365.570000      0.0      0.0   2650.37    2650.37
3344  1.0   163.79   26.210000      0.0      0.0    190.00     190.00
3345  1.0     0.00    0.000000      0.0      0.0      0.00       0.00
3346  1.0  1082.00    0.000000      0.0      0.0   1239.10    1333.00

[3342 rows x 7 columns]

In [96]:
df5_iqr.to_csv("Datos_limpios.csv")

In [97]:
from google.colab import files


files.download("Datos_limpios.csv")

In [98]:
df_limpio= pd.read_excel('Gastos y costos 20-23.xlsx', sheet_name = '2023')
df_limpio

,CALOR Y CONTROL S.A DE C.V,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,SUMA GTO,1558002.16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,DEDUCCIONES 2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUMA IVA,197471.85,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
3,2023-01-01 00:00:00,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1,0,0,0,0,NaN,0,0,P,Vigente,NaN
4,2023-01-01 00:00:00,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1,0,0,0,0,NaN,0,0,P,Vigente,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,2023-02-01 00:00:00,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,03,1,0,0,0,0,NaN,0,0,I,Vigente,NaN
396,2023-02-01 00:00:00,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,01,1,220,0,0,0,NaN,220,220,I,Vigente,NaN
397,2023-02-01 00:00:00,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,03,1,18071.52,682.4,0,0,NaN,18753.92,18753.92,I,Vigente,NaN
398,2023-02-01 00:00:00,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,05,1,14472.32,0,0,0,NaN,14472.32,14472.32,I,Vigente,NaN
399,2023-02-01 00:00:00,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1,0,0,0,0,NaN,0,0,P,Vigente,NaN